apiVersion: v1
kind: Service
metadata:
  name: node-guestbook-app
  labels:
    app: node-guestbook
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: node-guestbook
    tier: frontend
  ports:
    - port: 80
      targetPort: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-guestbook-apk
  labels:
    app: node-guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: node-guestbook
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: vsvydenko/node-guestbook-app
        ports:
        - name: http-server
          containerPort: 8080
